### ISSUE TITLE
Add uci snapshot support

### ISSUE THREAD

**Issue by blogic** [blogic/udrone#2]
Running tests will fiddle with the uci settings of the drone. Add a feature to snapshot /etc/config/. Each time t drone receives a !reset command it shall restore the snapshot and call reload_config.

**Comment by aparcar** [comment]
This can be done via the `cmd_system.c` call and running `firstboot`. The `udrone` package should automatically set reasonable UCI defaults, like disabling DHCP on the LAN interface.
